# About: Test image for Simple object detection.
# Created by Wengjiakang at 24.11.2023

FROM ubuntu:18.04
# Add sources.list /etc/apt/
RUN apt-get update && apt-get install -y \
        software-properties-common \
        net-tools iputils-ping iproute2 telnet sudo git wget zip \
        libsm6 libxext6 libfontconfig1 libxrender1 libgl1-mesa-glx
# Python3 requirements
# RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install -y python3 python3-dev python3-pip
RUN sudo apt-get install -y libsndfile1 ffmpeg
RUN sudo -H pip3 install -U pip
RUN sudo -H pip install -U pip

# Source for the users in China, please uncomment this line
# RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

RUN pip3 install --default-timeout=1000 numpy==1.15.0
RUN pip3 install --default-timeout=1000 scipy==0.19.0
RUN pip3 install --default-timeout=1000 scikit-learn==0.24.1
RUN pip3 install --default-timeout=1000 museval==0.2.0
RUN pip3 install --default-timeout=1000 pandas cffi progressbar2 scapy librosa torch==1.8.1 torchvision==0.9.1 torchaudio==0.8.1  --no-cache-dir

WORKDIR /app/simple-emu

USER root

CMD ["bash"]